name: Update gist with WakaTime summary
on:
  schedule:
    - cron: '40 1 * * *'
  workflow_dispatch:
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: superman66/wakatime-sync@master
        env:
          GH_TOKEN: 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
          GIST_ID: 052c5ee0aa63285fe73e2c0be3bb197a
          WAKATIME_API_KEY: waka_de9eeeb2-8feb-43a6-99f5-95b300de3712
          SCU_KEY: ${{ secrets.SCU_KEY }}
